[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 20


[[headers]]
for = "https://hiking-photos-66kz.onrender.com/*"
[headers.values]
Access-Control-Allow-Origin = "https://hiking-photos-66kz.onrender.com/*"